package org.openehr;

/**
 * Created by verhees on 28-6-17.
 */
public class CKMRoundtripTest {
    "openEHR-DEMOGRAPHIC-ADDRESS.address.v1.adl",
    "openEHR-DEMOGRAPHIC-ADDRESS.address-provider.v1.adl",
    openEHR-DEMOGRAPHIC-ADDRESS.electronic_communication.v1.adl
    openEHR-DEMOGRAPHIC-ADDRESS.electronic_communication-provider.v1.adl
    openEHR-DEMOGRAPHIC-CAPABILITY.individual_credentials.v1.adl
    openEHR-DEMOGRAPHIC-CLUSTER.biometric_identifier_iso.v1.adl
    openEHR-DEMOGRAPHIC-CLUSTER.birth_data_additional_detail_br.v1.adl
    openEHR-DEMOGRAPHIC-CLUSTER.high_level_address_other_data_br.v1.adl
    openEHR-DEMOGRAPHIC-CLUSTER.identifier_other_details.v1.adl
    openEHR-DEMOGRAPHIC-CLUSTER.individual_credentials_iso.v1.adl
    openEHR-DEMOGRAPHIC-CLUSTER.individual_provider_credentials_iso.v1.adl
    openEHR-DEMOGRAPHIC-CLUSTER.person_additional_data_br.v1.adl
    openEHR-DEMOGRAPHIC-CLUSTER.person_additional_data_iso.v1.adl
    openEHR-DEMOGRAPHIC-CLUSTER.person_birth_data_iso.v1.adl
    openEHR-DEMOGRAPHIC-CLUSTER.person_death_data_iso.v1.adl
    openEHR-DEMOGRAPHIC-CLUSTER.person_identifier.v1.adl
    openEHR-DEMOGRAPHIC-CLUSTER.person_identifier-provider.v1.adl
    openEHR-DEMOGRAPHIC-CLUSTER.person_other_birth_data_br.v1.adl
    openEHR-DEMOGRAPHIC-CLUSTER.person_other_death_data.v1.adl
    openEHR-DEMOGRAPHIC-CLUSTER.provider_identifier.v1.adl
    openEHR-DEMOGRAPHIC-CLUSTER.registration_other_data.v1.adl
    openEHR-DEMOGRAPHIC-ITEM_TREE.person_details.v1.adl
    openEHR-DEMOGRAPHIC-ORGANISATION.organisation.v1.adl
    openEHR-DEMOGRAPHIC-PARTY_IDENTITY.organisation_name.v1.adl
    openEHR-DEMOGRAPHIC-PARTY_IDENTITY.person_name.v1.adl
    openEHR-DEMOGRAPHIC-PARTY_IDENTITY.person_name-individual_provider.v1.adl
    openEHR-DEMOGRAPHIC-PERSON.person.v1.adl
    openEHR-DEMOGRAPHIC-PERSON.person-patient.v1.adl
    openEHR-DEMOGRAPHIC-ROLE.healthcare_consumer.v1.adl
    openEHR-DEMOGRAPHIC-ROLE.healthcare_provider_organisation.v1.adl
    openEHR-DEMOGRAPHIC-ROLE.individual_provider.v1.adl
    openEHR-DEMOGRAPHIC-ROLE.third_party_payer.v1.adl
    openEHR-EHR-ACTION.care_plan.v0.adl
    openEHR-EHR-ACTION.health_education.v1.adl
    openEHR-EHR-ACTION.imaging_exam.v0.adl
    openEHR-EHR-ACTION.informed_consent.v1.adl
    openEHR-EHR-ACTION.medication.v0.adl
    openEHR-EHR-ACTION.procedure.v1.adl
    openEHR-EHR-ACTION.review.v1.adl
    openEHR-EHR-ACTION.transfusion.v1.adl
    openEHR-EHR-ADMIN_ENTRY.admission.v1.adl
    openEHR-EHR-CLUSTER.address.v1.adl
    openEHR-EHR-CLUSTER.anatomical_location.v1.adl
    openEHR-EHR-CLUSTER.anatomical_location_clock.v0.adl
    openEHR-EHR-CLUSTER.anatomical_location_relative.v1.adl
    openEHR-EHR-CLUSTER.asa_status.v0.adl
    openEHR-EHR-CLUSTER.auscultation_lung.v0.adl
    openEHR-EHR-CLUSTER.case_identification.v1.adl
    openEHR-EHR-CLUSTER.cessation_attempts.v1.adl
    openEHR-EHR-CLUSTER.change.v1.adl
    openEHR-EHR-CLUSTER.citation.v1.adl
    openEHR-EHR-CLUSTER.clinical_evidence.v1.adl
    openEHR-EHR-CLUSTER.conditional_medication_rules.v0.adl
    openEHR-EHR-CLUSTER.consent_details.v1.adl
    openEHR-EHR-CLUSTER.cormack_lehane.v1.adl
    openEHR-EHR-CLUSTER.device.v1.adl
    openEHR-EHR-CLUSTER.device_details.v1.adl
    openEHR-EHR-CLUSTER.dietary_nutrients.v0.adl
    openEHR-EHR-CLUSTER.dietary_phytochemicals.v0.adl
    openEHR-EHR-CLUSTER.distribution.v1.adl
    openEHR-EHR-CLUSTER.dosage_administration.v0.adl
    openEHR-EHR-CLUSTER.environmental_conditions.v1.adl
    openEHR-EHR-CLUSTER.exam.v0.adl
    openEHR-EHR-CLUSTER.exam_abdomen.v0.adl
    openEHR-EHR-CLUSTER.exam_anus.v0.adl
    openEHR-EHR-CLUSTER.exam_breast.v0.adl
    openEHR-EHR-CLUSTER.exam_breasts.v0.adl
    openEHR-EHR-CLUSTER.exam_burn.v0.adl
    openEHR-EHR-CLUSTER.exam_chest.v0.adl
    openEHR-EHR-CLUSTER.exam_cranial_nerves.v0.adl
    openEHR-EHR-CLUSTER.exam_eye.v0.adl
    openEHR-EHR-CLUSTER.exam_eye_anterior.v0.adl
    openEHR-EHR-CLUSTER.exam_eye_aqueous.v0.adl
    openEHR-EHR-CLUSTER.exam_eye_lens.v0.adl
    openEHR-EHR-CLUSTER.exam_eye_posterior.v0.adl
    openEHR-EHR-CLUSTER.exam_eye_pupil.v0.adl
    openEHR-EHR-CLUSTER.exam_eye_retina.v0.adl
    openEHR-EHR-CLUSTER.exam_eye_vitreous.v0.adl
    openEHR-EHR-CLUSTER.exam_eyes.v0.adl
    openEHR-EHR-CLUSTER.exam_gait.v0.adl
    openEHR-EHR-CLUSTER.exam_heart.v0.adl
    openEHR-EHR-CLUSTER.exam_lesion.v0.adl
    openEHR-EHR-CLUSTER.exam_lip.v0.adl
    openEHR-EHR-CLUSTER.exam_lips.v0.adl
    openEHR-EHR-CLUSTER.exam_lung.v0.adl
    openEHR-EHR-CLUSTER.exam_lungs.v0.adl
    openEHR-EHR-CLUSTER.exam_mouth.v0.adl
    openEHR-EHR-CLUSTER.exam_nervous_system.v0.adl
    openEHR-EHR-CLUSTER.exam_pattern.v0.adl
    openEHR-EHR-CLUSTER.exam_penis.v0.adl
    openEHR-EHR-CLUSTER.exam_scrotum.v0.adl
    openEHR-EHR-CLUSTER.exam_skin.v0.adl
    openEHR-EHR-CLUSTER.exam_tongue.v0.adl
    openEHR-EHR-CLUSTER.exam_urethra.v0.adl
    openEHR-EHR-CLUSTER.exam_vulva.v0.adl
    openEHR-EHR-CLUSTER.exam_wound.v0.adl
    openEHR-EHR-CLUSTER.exclusion_exam.v1.adl
    openEHR-EHR-CLUSTER.exclusion_symptom_sign.v0.adl
    openEHR-EHR-CLUSTER.family_prevalence.v1.adl
    openEHR-EHR-CLUSTER.free_text.v0.adl
    openEHR-EHR-CLUSTER.health_event.v0.adl
    openEHR-EHR-CLUSTER.health_event-poisoning.v1.adl
    openEHR-EHR-CLUSTER.health_event-trauma.v1.adl
    openEHR-EHR-CLUSTER.hip_arthroplasty_component.v1.adl
    openEHR-EHR-CLUSTER.histopathology_findings.v0.adl
    openEHR-EHR-CLUSTER.household.v0.adl
    openEHR-EHR-CLUSTER.housing.v0.adl
    openEHR-EHR-CLUSTER.hydration.v1.adl
    openEHR-EHR-CLUSTER.imaging.v1.adl
    openEHR-EHR-CLUSTER.imaging_result.v0.adl
    openEHR-EHR-CLUSTER.individual_personal.v1.adl
    openEHR-EHR-CLUSTER.individual_professional.v1.adl
    openEHR-EHR-CLUSTER.inspection_body_fluid.v0.adl
    openEHR-EHR-CLUSTER.inspection_cervix.v0.adl
    openEHR-EHR-CLUSTER.inspection_rectum.v0.adl
    openEHR-EHR-CLUSTER.inspection_vagina.v0.adl
    openEHR-EHR-CLUSTER.inspired_oxygen.v0.adl
    openEHR-EHR-CLUSTER.interpreter_details.v1.adl
    openEHR-EHR-CLUSTER.issue.v1.adl
    openEHR-EHR-CLUSTER.laboratory_test_panel.v0.adl
    openEHR-EHR-CLUSTER.level_of_exertion.v1.adl
    openEHR-EHR-CLUSTER.lymph_node_metastases.v1.adl
    openEHR-EHR-CLUSTER.macronutrients.v0.adl
    openEHR-EHR-CLUSTER.macroscopy_colorectal_carcinoma.v1.adl
    openEHR-EHR-CLUSTER.macroscopy_lung_carcinoma.v1.adl
    openEHR-EHR-CLUSTER.medication_authorisation.v0.adl
    openEHR-EHR-CLUSTER.medication_order_summary.v0.adl
    openEHR-EHR-CLUSTER.medication_substance.v0.adl
    openEHR-EHR-CLUSTER.medication_supply_amount.v0.adl
    openEHR-EHR-CLUSTER.micronutrients.v0.adl
    openEHR-EHR-CLUSTER.microscopy_breast_carcinoma.v1.adl
    openEHR-EHR-CLUSTER.microscopy_colorectal_carcinoma.v1.adl
    openEHR-EHR-CLUSTER.microscopy_lung_carcinoma.v1.adl
    openEHR-EHR-CLUSTER.microscopy_lymphoma.v1.adl
    openEHR-EHR-CLUSTER.microscopy_melanoma.v1.adl
    openEHR-EHR-CLUSTER.microscopy_prostate_carcinoma.v1.adl
    openEHR-EHR-CLUSTER.move.v1.adl
    openEHR-EHR-CLUSTER.move-joint.v1.adl
    openEHR-EHR-CLUSTER.move-spine.v1.adl
    openEHR-EHR-CLUSTER.multimedia.v1.adl
    openEHR-EHR-CLUSTER.notifiable_condition.v1.adl
    openEHR-EHR-CLUSTER.nyha_heart_failure.v1.adl
    openEHR-EHR-CLUSTER.occupation.v0.adl
    openEHR-EHR-CLUSTER.oedema.v0.adl
    openEHR-EHR-CLUSTER.organisation.v1.adl
    openEHR-EHR-CLUSTER.outbreak_identification.v1.adl
    openEHR-EHR-CLUSTER.palpation_prostate.v0.adl
    openEHR-EHR-CLUSTER.palpation_rectum.v0.adl
    openEHR-EHR-CLUSTER.palpation_testicle.v0.adl
    openEHR-EHR-CLUSTER.palpation_vagina.v0.adl
    openEHR-EHR-CLUSTER.percussion.v1.adl
    openEHR-EHR-CLUSTER.person_name.v1.adl
    openEHR-EHR-CLUSTER.physical_properties.v0.adl
    openEHR-EHR-CLUSTER.precise_location.v1.adl
    openEHR-EHR-CLUSTER.problem_status.v0.adl
    openEHR-EHR-CLUSTER.professional_role.v1.adl
    openEHR-EHR-CLUSTER.refraction_details.v1.adl
    openEHR-EHR-CLUSTER.religion.v1.adl
    openEHR-EHR-CLUSTER.sense_of_smell.v1.adl
    openEHR-EHR-CLUSTER.specimen.v0.adl
    openEHR-EHR-CLUSTER.specimen_container.v0.adl
    openEHR-EHR-CLUSTER.specimen_preparation.v0.adl
    openEHR-EHR-CLUSTER.symptom_sign.v1.adl
    openEHR-EHR-CLUSTER.synthesis_lymphoma.v1.adl
    openEHR-EHR-CLUSTER.telecom_details.v0.adl
    openEHR-EHR-CLUSTER.therapeutic_direction.v1.adl
    openEHR-EHR-CLUSTER.timing_daily.v0.adl
    openEHR-EHR-CLUSTER.timing_repetition.v0.adl
    openEHR-EHR-CLUSTER.tnm_stage_clinical.v0.adl
    openEHR-EHR-CLUSTER.tnm_stage_pathological.v0.adl
    openEHR-EHR-CLUSTER.tnm_staging.v1.adl
    openEHR-EHR-CLUSTER.tnm_staging-breast.v1.adl
    openEHR-EHR-CLUSTER.tnm_staging-colorectal.v1.adl
    openEHR-EHR-CLUSTER.tnm_staging-lung_cancer.v1.adl
    openEHR-EHR-CLUSTER.tnm_staging-melanoma.v1.adl
    openEHR-EHR-CLUSTER.tnm_staging-prostate.v1.adl
    openEHR-EHR-CLUSTER.tnm_staging_7th.v1.adl
    openEHR-EHR-CLUSTER.tnm_staging_7th-breast.v1.adl
    openEHR-EHR-CLUSTER.tnm_staging_7th-colorectal.v1.adl
    openEHR-EHR-CLUSTER.tnm_staging_7th-lung.v1.adl
    openEHR-EHR-CLUSTER.tnm_staging_7th-lymphoma.v1.adl
    openEHR-EHR-CLUSTER.tnm_staging_7th-melanoma.v1.adl
    openEHR-EHR-CLUSTER.tnm_staging_7th-prostate.v1.adl
    openEHR-EHR-CLUSTER.tumour_colorectal_staging_non_tnm.v1.adl
    openEHR-EHR-CLUSTER.tumour_invasion.v1.adl
    openEHR-EHR-CLUSTER.tumour_resection_margins.v1.adl
    openEHR-EHR-CLUSTER.waveform.v1.adl
    openEHR-EHR-COMPOSITION.adverse_reaction_list.v1.adl
    openEHR-EHR-COMPOSITION.encounter.v1.adl
    openEHR-EHR-COMPOSITION.event_summary.v1.adl
    openEHR-EHR-COMPOSITION.health_summary.v1.adl
    openEHR-EHR-COMPOSITION.medication_list.v0.adl
    openEHR-EHR-COMPOSITION.notification.v0.adl
    openEHR-EHR-COMPOSITION.prescription.v0.adl
    openEHR-EHR-COMPOSITION.problem_list.v1.adl
    openEHR-EHR-COMPOSITION.report.v1.adl
    openEHR-EHR-COMPOSITION.report-procedure.v1.adl
    openEHR-EHR-COMPOSITION.report-result.v1.adl
    openEHR-EHR-COMPOSITION.request.v1.adl
    openEHR-EHR-COMPOSITION.review.v1.adl
    openEHR-EHR-COMPOSITION.self_monitoring.v0.adl
    openEHR-EHR-COMPOSITION.transfer_summary.v1.adl
    openEHR-EHR-COMPOSITION.vaccination_list.v1.adl
    openEHR-EHR-EVALUATION.absence.v1.adl
    openEHR-EHR-EVALUATION.advance_decision_refuse_treatment_uk.v1.adl
    openEHR-EHR-EVALUATION.adverse_reaction_risk.v1.adl
    openEHR-EHR-EVALUATION.alcohol_use_summary.v0.adl
    openEHR-EHR-EVALUATION.citation.v0.adl
    openEHR-EHR-EVALUATION.clinical_synopsis.v1.adl
    openEHR-EHR-EVALUATION.consumer_note.v0.adl
    openEHR-EHR-EVALUATION.container.v0.adl
    openEHR-EHR-EVALUATION.contraindication.v0.adl
    openEHR-EHR-EVALUATION.device_summary.v0.adl
    openEHR-EHR-EVALUATION.exclusion_global.v1.adl
    openEHR-EHR-EVALUATION.exclusion_specific.v1.adl
    openEHR-EHR-EVALUATION.family_history.v2.adl
    openEHR-EHR-EVALUATION.goal.v1.adl
    openEHR-EHR-EVALUATION.health_risk.v1.adl
    openEHR-EHR-EVALUATION.infant_feeding.v0.adl
    openEHR-EHR-EVALUATION.infectious_disease_summary.v1.adl
    openEHR-EHR-EVALUATION.medication_summary.v0.adl
    openEHR-EHR-EVALUATION.menstrual_cycle_summary.v0.adl
    openEHR-EHR-EVALUATION.obstetric_summary.v0.adl
    openEHR-EHR-EVALUATION.precaution.v1.adl
    openEHR-EHR-EVALUATION.pregnancy_bf_status.v1.adl
    openEHR-EHR-EVALUATION.pregnancy_summary.v0.adl
    openEHR-EHR-EVALUATION.problem_diagnosis.v1.adl
    openEHR-EHR-EVALUATION.reason_for_encounter.v1.adl
    openEHR-EHR-EVALUATION.recommendation.v1.adl
    openEHR-EHR-EVALUATION.smokeless_tobacco_summary.v0.adl
    openEHR-EHR-EVALUATION.social_summary.v1.adl
    openEHR-EHR-EVALUATION.source.v1.adl
    openEHR-EHR-EVALUATION.test.v0.adl
    openEHR-EHR-EVALUATION.tobacco_smoking_summary.v1.adl
    openEHR-EHR-EVALUATION.triage.v1.adl
    openEHR-EHR-EVALUATION.vaccination_summary.v1.adl
    openEHR-EHR-INSTRUCTION.care_plan.v0.adl
    openEHR-EHR-INSTRUCTION.health_education.v0.adl
    openEHR-EHR-INSTRUCTION.informed_consent.v1.adl
    openEHR-EHR-INSTRUCTION.medication_order.v1.adl
    openEHR-EHR-INSTRUCTION.notification.v0.adl
    openEHR-EHR-INSTRUCTION.request.v0.adl
    openEHR-EHR-INSTRUCTION.request-imaging_exam.v1.adl
    openEHR-EHR-INSTRUCTION.request-lab_test.v1.adl
    openEHR-EHR-INSTRUCTION.request-procedure.v0.adl
    openEHR-EHR-INSTRUCTION.transfusion.v0.adl
    openEHR-EHR-OBSERVATION.apgar.v1.adl
    openEHR-EHR-OBSERVATION.audiogram.v1.adl
    openEHR-EHR-OBSERVATION.autopsy.v1.adl
    openEHR-EHR-OBSERVATION.avpu.v1.adl
    openEHR-EHR-OBSERVATION.barthel.v1.adl
    openEHR-EHR-OBSERVATION.blood_match.v1.adl
    openEHR-EHR-OBSERVATION.blood_pressure.v1.adl
    openEHR-EHR-OBSERVATION.body_mass_index.v1.adl
    openEHR-EHR-OBSERVATION.body_segment.v0.adl
    openEHR-EHR-OBSERVATION.body_surface_area.v0.adl
    openEHR-EHR-OBSERVATION.body_temperature.v2.adl
    openEHR-EHR-OBSERVATION.body_weight.v1.adl
    openEHR-EHR-OBSERVATION.body_weight-adjusted.v1.adl
    openEHR-EHR-OBSERVATION.body_weight-birth.v1.adl
    openEHR-EHR-OBSERVATION.braden_scale.v1.adl
    openEHR-EHR-OBSERVATION.braden_scale-child.v1.adl
    openEHR-EHR-OBSERVATION.braden_scale_neonate.v1.adl
    openEHR-EHR-OBSERVATION.bristol_stool_scale.v1.adl
    openEHR-EHR-OBSERVATION.ccs_angina_status.v1.adl
    openEHR-EHR-OBSERVATION.cgas.v1.adl
    openEHR-EHR-OBSERVATION.child_growth.v0.adl
    openEHR-EHR-OBSERVATION.comfort_behaviour_scale.v0.adl
    openEHR-EHR-OBSERVATION.conference.v1.adl
    openEHR-EHR-OBSERVATION.container.v0.adl
    openEHR-EHR-OBSERVATION.critical_pain_observation_tool.v0.adl
    openEHR-EHR-OBSERVATION.demo.v1.adl
    openEHR-EHR-OBSERVATION.diabetic_wound_wagner.v1.adl
    openEHR-EHR-OBSERVATION.easi_score.v1.adl
    openEHR-EHR-OBSERVATION.ecg.v0.adl
    openEHR-EHR-OBSERVATION.ecog.v0.adl
    openEHR-EHR-OBSERVATION.edinburgh_pnd_scale.v1.adl
    openEHR-EHR-OBSERVATION.exam.v1.adl
    openEHR-EHR-OBSERVATION.faeces.v1.adl
    openEHR-EHR-OBSERVATION.fagerstrom.v0.adl
    openEHR-EHR-OBSERVATION.fetal_heart.v1.adl
    openEHR-EHR-OBSERVATION.fetal_heart-monitoring.v1.adl
    openEHR-EHR-OBSERVATION.fetal_movement.v1.adl
    openEHR-EHR-OBSERVATION.fitzpatrick_skin_type.v1.adl
    openEHR-EHR-OBSERVATION.fluid_balance.v0.adl
    openEHR-EHR-OBSERVATION.fluid_input.v0.adl
    openEHR-EHR-OBSERVATION.fluid_output.v0.adl
    openEHR-EHR-OBSERVATION.fundoscopic_examination.v1.adl
    openEHR-EHR-OBSERVATION.glasgow_coma-paed.v1.adl
    openEHR-EHR-OBSERVATION.glasgow_coma_scale.v1.adl
    openEHR-EHR-OBSERVATION.hannallah_pain_scale.v0.adl
    openEHR-EHR-OBSERVATION.harris_hip_score.v1.adl
    openEHR-EHR-OBSERVATION.head_circumference.v0.adl
    openEHR-EHR-OBSERVATION.height.v1.adl
    openEHR-EHR-OBSERVATION.hip_circumference.v0.adl
    openEHR-EHR-OBSERVATION.honos.v0.adl
    openEHR-EHR-OBSERVATION.humpty_dumpty_falls_risk_assessment_tool.v0.adl
    openEHR-EHR-OBSERVATION.iga_eczema_treat.v1.adl
    openEHR-EHR-OBSERVATION.imaging_exam.v0.adl
    openEHR-EHR-OBSERVATION.indirect_oximetry.v0.adl
    openEHR-EHR-OBSERVATION.infant_feeding.v0.adl
    openEHR-EHR-OBSERVATION.intraocular_pressure.v0.adl
    openEHR-EHR-OBSERVATION.intravascular_pressure.v0.adl
    openEHR-EHR-OBSERVATION.intravascular_pressure-cvp.v1.adl
    openEHR-EHR-OBSERVATION.intravascular_pressure-jvp.v1.adl
    openEHR-EHR-OBSERVATION.laboratory_test.v0.adl
    openEHR-EHR-OBSERVATION.malinas_score.v0.adl
    openEHR-EHR-OBSERVATION.mantoux.v1.adl
    openEHR-EHR-OBSERVATION.menstrual_cycle.v0.adl
    openEHR-EHR-OBSERVATION.msfc_score.v1.adl
    openEHR-EHR-OBSERVATION.mst.v0.adl
    openEHR-EHR-OBSERVATION.must.v0.adl
    openEHR-EHR-OBSERVATION.news_uk_rcp.v1.adl
    openEHR-EHR-OBSERVATION.nine_hole_peg_test.v1.adl
    openEHR-EHR-OBSERVATION.oucher_pain_scale.v0.adl
    openEHR-EHR-OBSERVATION.paced_auditory_serial_addition_test.v1.adl
    openEHR-EHR-OBSERVATION.pathology_test.v1.adl
    openEHR-EHR-OBSERVATION.pathology_test-blood_glucose.v1.adl
    openEHR-EHR-OBSERVATION.pathology_test-lipids.v1.adl
    openEHR-EHR-OBSERVATION.patients_global_assessment_eczema_treat.v1.adl
    openEHR-EHR-OBSERVATION.penetration_aspiration_scale.v1.adl
    openEHR-EHR-OBSERVATION.poem_score.v0.adl
    openEHR-EHR-OBSERVATION.pregnancy_test.v1.adl
    openEHR-EHR-OBSERVATION.pulmonary_function.v0.adl
    openEHR-EHR-OBSERVATION.pulse.v1.adl
    openEHR-EHR-OBSERVATION.pulse_deficit.v0.adl
    openEHR-EHR-OBSERVATION.refraction.v0.adl
    openEHR-EHR-OBSERVATION.respiration.v1.adl
    openEHR-EHR-OBSERVATION.richmond_agitation_sedation_scale.v0.adl
    openEHR-EHR-OBSERVATION.sara_scale.v0.adl
    openEHR-EHR-OBSERVATION.scorad_score.v1.adl
    openEHR-EHR-OBSERVATION.speech.v1.adl
    openEHR-EHR-OBSERVATION.story.v1.adl
    openEHR-EHR-OBSERVATION.stroke_scale_neurological_assessment.v0.adl
    openEHR-EHR-OBSERVATION.substance_use.v1.adl
    openEHR-EHR-OBSERVATION.substance_use-alcohol.v1.adl
    openEHR-EHR-OBSERVATION.substance_use-caffeine.v1.adl
    openEHR-EHR-OBSERVATION.substance_use-tobacco.v1.adl
    openEHR-EHR-OBSERVATION.tanner.v0.adl
    openEHR-EHR-OBSERVATION.temperature.v1.adl
    openEHR-EHR-OBSERVATION.tendon_babinski_reflexes.v1.adl
    openEHR-EHR-OBSERVATION.third_party_observation.v1.adl
    openEHR-EHR-OBSERVATION.timed_25_foot_walk.v1.adl
    openEHR-EHR-OBSERVATION.urinalysis.v1.adl
    openEHR-EHR-OBSERVATION.uterine_contractions.v1.adl
    openEHR-EHR-OBSERVATION.visual_acuity.v0.adl
    openEHR-EHR-OBSERVATION.visual_field_measurement.v1.adl
    openEHR-EHR-OBSERVATION.waist_circumference.v0.adl
    openEHR-EHR-OBSERVATION.waist_hip_ratio.v0.adl
    openEHR-EHR-OBSERVATION.waterlow_score.v1.adl
    openEHR-EHR-SECTION.adhoc.v1.adl
    openEHR-EHR-SECTION.adverse_list.v1.adl
    openEHR-EHR-SECTION.conclusion.v1.adl
    openEHR-EHR-SECTION.diagnostic_reports.v1.adl
    openEHR-EHR-SECTION.medication_order_list.v1.adl
    openEHR-EHR-SECTION.problem_list.v1.adl
    openEHR-EHR-SECTION.referral_details.v1.adl
    openEHR-EHR-SECTION.soap.v1.adl
    openEHR-EHR-SECTION.vital_signs.v0.adl
}
